version: '3.7'

services:
  postgresql:
    image: postgres:15.4
    ports:
      - 5431:5432
    volumes:
       - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=timecard
      - POSTGRES_PASSWORD=timecard
      - POSTGRES_DB=timecard

volumes:
  postgres-data:
