version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    image: timecard_dev:latest
    volumes:
      - ./:/usr/src/app
    ports:
      - '8000:8000'
    env_file:
      - ./docker/dev/dev.env
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15.4
    ports:
      - '5432:5432'
    volumes:
       - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=timecard
      - POSTGRES_PASSWORD=timecard
      - POSTGRES_DB=timecard

volumes:
  postgres-data:
