name: 'Setup Pipenv'
description: 'Set up Pipenv for Python projects'
runs:
  using: 'composite'
  steps:
    - name: Install Pipenv
      shell: bash
      run: | 
        pip install --upgrade pip
        pip install pipenv

    - name: Cache Pipenv virtual environment
      uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install Dependencies (Including dev packages)
      shell: bash
      run: |
        pipenv sync --dev
