version: '3.8'

services:
  web:
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile
    image: timecard_prod:latest
    expose:
      - 8000
    env_file:
      - ../dev/dev.env  # ./prod.env
    depends_on:
      - postgresql
    volumes:
      - static_volume:/home/app/web/static

  nginx:
    build:
      context: ../../
      dockerfile: ./docker/prod/nginx/Dockerfile
    image: timecard_nginx:latest
    ports:
      - '80:80'
    depends_on:
      - web
    volumes:
      - static_volume:/usr/share/nginx/html/static

  postgresql:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=timecard
      - POSTGRES_PASSWORD=timecard
      - POSTGRES_DB=timecard
    expose:
      - 5432
    ports:
      - '5432:5432'

volumes:
  postgres_data:
  static_volume:
