# Generated by Django 3.1.3 on 2020-11-04 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('seconds_paused', models.PositiveIntegerField(default=0)),
                ('pause_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('unverified', 'Unverified')], default='unverified', max_length=24)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('hours', models.DecimalField(decimal_places=5, default=0, max_digits=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
