# Generated by Django 3.1.3 on 2020-11-21 19:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_pause', models.DateTimeField(blank=True, null=True)),
                ('end_pause', models.DateTimeField(blank=True, null=True)),
                ('time_paused', models.DurationField(default=datetime.timedelta(0))),
                ('time_worked', models.DurationField(default=datetime.timedelta(0))),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('unverified', 'Unverified'), ('needs_approval', 'Needs Approval'), ('flagged', 'Flagged')], default='unverified', max_length=24)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
