# Generated by Django 3.1.7 on 2021-04-01 23:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_pause', models.DateTimeField(blank=True, null=True)),
                ('end_pause', models.DateTimeField(blank=True, null=True)),
                ('time_paused', models.DurationField(default=datetime.timedelta(0))),
                ('time_worked', models.DurationField(default=datetime.timedelta(0))),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('needs_approval', 'Needs Approval'), ('flagged', 'Flagged'), ('active', 'Active')], default='active', max_length=24)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='EntryLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('loc_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('loc_errors', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='entries.entry')),
            ],
        ),
    ]
