# Generated by Django 3.2.4 on 2021-07-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20210615_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
