name: Build Images and Deploy to Production

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform cloud
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.5"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Apply
        run: |
          cd terraform/production && 
          terraform init &&
          terraform apply -var="web_version=${{ github.ref_name }}" -var="nginx_version=${{ github.ref_name }}" --auto-approve  
