name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Initialize
        run: terraform init
        env:
          TF_API_TOKEN: ${{ secrets.TERRAFORM_API_TOKEN }}

      - name: Terraform Destroy
        run: | 
          cd terraform/staging &&
          terraform init &&
          terraform destroy --auto-approve
