name: Python CI and Django Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.14
        env:
          POSTGRES_USER: timecard
          POSTGRES_PASSWORD: timecard
          POSTGRES_DB: timecard
        ports:
          - 5431:5432
        volumes:
          - postgres-data:/var/lib/postgresql/data/
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Setup Pipenv
      uses: ./.github/actions/setup-pipenv

    - name: Run Django Tests
      run: pipenv run python manage.py test -v 2 --settings timecard.settings.test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Setup Pipenv
        uses: ./.github/actions/setup-pipenv

      - name: Lint with flake8
        run: |
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=migrations

  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Setup Pipenv
        uses: ./.github/actions/setup-pipenv

      - name: Static Code Analysis with bandit
        run: pipenv run bandit -r .

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Setup Pipenv
        uses: ./.github/actions/setup-pipenv

      - name: Check Dependencies with pipenv
        run: pipenv check
